package:
  name: r-scplotter
  version: 0.6.1

source:
  path: ..

build:
  number: 4
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    # commented requirements are already required by plotthis

    # Imports:
    - r-base
    - r-callr
    - r-seuratobject
    - pwwang::bioconductor-screpertoire
    # - r-circlize
    # - r-dplyr
    # - r-scales
    # - r-ggnewscale
    # - r-ggplot2
    # - r-rlang
    # - r-stringr
    # - r-tidyr
    - pwwang::r-plotthis>=0.7.4
    # - r-r6

    # Suggests:
    # - r-clustree
    # - r-concaveman
    # - r-ggalluvial
    # - r-ggforce
    # - r-ggpubr
    # - r-ggraph
    # - r-ggridges
    # - r-ggupset
    # - r-ggvenndiagram
    # - r-ggwordcloud
    - r-gridgraphics
    # - r-hexbin
    - r-metap
    # - r-igraph
    # - r-inext
    # - r-scattermore
    - r-seurat
    # - bioconda::bioconductor-complexheatmap
    # - pwwang::r-gglogger
    - pwwang::r-tidyprompt

  run:
    - r-base
    - r-callr
    - r-seuratobject
    - pwwang::bioconductor-screpertoire
    - pwwang::r-plotthis>=0.7.4
    - r-gridgraphics
    - r-metap
    - r-seurat
    - r-tidyprompt

test:
  commands:
    - $R -e "library('scplotter')"

about:
  home: https://github.com/pwwang/scplotter
  license: GPL-3
  summary: provides a set of functions to visualize single-cell sequencing data in an easy and efficient way.
  license_family: GPL
  license_file: LICENSE.md
