---
title: "Basic Design Of The Plots"
---

This document introduces the basic design of the plots generated by `scplotter`, which helps you to better use the package to generate plots that meet your needs.

This package is aimed at providing a set of plotting functions, instead of doing the real analysis. Data transformation is performed in some functions, which is necessary to generate the plots. However, the package does not provide functions for real data analysis.

## Color palettes

The package provides a set of color palettes that are widely used. They are from different packages or used in different tools, including:

- `viridis` from the [`viridis`][1] package
- `brewer.pal.info` from the [`RColorBrewer`][2] package
- `ggsci_db` from the [`ggsci`][3] package
- `redmonder.pal.info` from the [`Redmonder`][4] package
- `metacartocolors` from the [`rcartocolor`][5] package
- `nord_palettes` from the [`nord`][6] package
- The `ocean` palettes of `syspals` from the [`pals`][7] package
- `colorschemes` from the [`dichromat`][8] package
- Some custom palettes including those from [`jcolors`][9] package

All the above palettes are provided by the [`SCP`][10] package. In addition, the `SCP` package also provides a set of color palettes that are widely used in single-cell analysis, including:

- The discrete colour palettes `DiscretePalette` from the [`Seurat`][11] package
- `scales::hue_pal` used by `Seurat`

[1]: https://cran.r-project.org/package=viridis
[2]: https://cran.r-project.org/package=RColorBrewer
[3]: https://cran.r-project.org/package=ggsci
[4]: https://cran.r-project.org/package=Redmonder
[5]: https://cran.r-project.org/package=rcartocolor
[6]: https://cran.r-project.org/package=nord
[7]: https://cran.r-project.org/package=pals
[8]: https://cran.r-project.org/package=dichromat
[9]: https://cran.r-project.org/package=jcolors
[10]: https://zhanghao-njmu.github.io/SCP/index.html
[11]: https://cran.r-project.org/package=Seurat

See also the following documentation for more details:

- [all available color palettes](../all-available-palettes.html)
- [`show_palettes`](../reference/show_palettes.html)
- [`palette_scp`](../reference/palette_scp.html)

## Basic implementation of the plotting functions

The plotting functions in `scplotter` are implemented with the following structure:

```r
SomePlot <- function(
    x,
    # The type of the plot
    plot_type,
    # The column to split the data and plot
    # When `facet` is TRUE, the columns specified here will be used to facet the plot
    # When `facet` is FALSE, the columns specified here will be used to split the data
    #   and generate multiple plots and combine them into one
    # If multiple columns are specified
    #   When `facet` is TRUE, up to 2 columns are allowed. If one column,
    #     `ggplot2::facet_wrap` is used, the number of rows and columns is determined
    #     by `nrow` and `ncol`
    #   When `facet` is FALSE, a warning will be issued and the columns will be
    #     concatenated into one column, using `split_by_sep` as the separator
    split_by, split_by_sep,
    # Columns to group the data for plotting
    # For those plotting functions that do not support multiple groups,
    # They will be concatenated into one column, using `group_by_sep` as the separator
    group_by, group_by_sep,
    # Whether to facet the plot, or split the data and combine the plots
    facet, facet_scales,
    # Controls for theming
    theme, theme_args, palette, palcolor, keep_empty, x_text_angle, aspect.ratio,
    legend.position, legend.direction, alpha, title, subtitle, xlab, ylab,
    # The number of rows and columns when `facet_wrap` is used or
    # when `facet` is FALSE, the number of rows and columns to combine the plots
    # For facet_wrap, dir = 'v' will be used when byrow = FALSE
    combine, nrow, ncol, byrow
    # Whether to guess the width and height of the plot in pixels
    # list(plot, width, height) will be returned instead of the plot if TRUE
    guess_size,
    # The resolution used to guess the size of the plot
    res,
    # Seed for random number generation
    seed,
    ...
) {

    # Argument validation

    # Data transformation
    #   Data will be transformed based on the arguments
    #   and split into a list of data frames by split_by

    # Plot for each split data frame
    plots <- lapply(split_data, function(df) {
        # Calling atomic plotting functions to generate the plot
        #   These functions do not need to handle split
        #   All data passed to these functions should feed to the plot
        SomePlotAtomic(df, ...)
    })

    # Combine the plots
    #     patch_work::wrap_plots(plots, nrow, ncol, byrow)
}

# The atomic plotting functions will not be exported by the package
SomePlotAtomic <- function(x, ...) UseMethod("plot_function_atomic")

SomePlotAtomic.default <- function(x, ...) {
    # The fallback function for atomic plotting for plot_types
}

SomePlotAtomic.<plot_type> <- function(x, ...) {
    # The specific atomic plotting function for plot_type
}
```

## Splitting vs faceting

The `split_by` argument is used to split the data and generate multiple plots. The `facet` argument is used to facet the plot. When `facet` is TRUE, the `split_by` columns will be used to facet the plot. When `facet` is FALSE, the `split_by` columns will be used to split the data and generate multiple plots, which will be combined into one plot.

For faceting, the `facet_scales` argument is used to control the scales of the facets. The `facet_wrap` function is used when `split_by` has one column; otherwise, the `facet_grid` function is used when `split_by` has two columns.

For splitting, the data will be split by the `split_by` columns and each split will be plotted separately. So each plot has its own scales and guides. Unlike faceting, the scales and guides are not shared between the plots.

## Types of plots based on the data

### Single-value plots

These plots are used to visualize a single value or a single value for each group.
These plots include:

- Bar plots (group_by works as x-axis)
- Pie charts (group_by works as slices)
- Line plots (group_by works as x-axis)

### Composition/Overlapping plots

- Bar plots with multiple groups (group1 works as x-axis, group2 works as fill, position could be either stack or dodge)
- Ring plots (multiple group_by columns supported as rings)
- Dot plots with multiple groups (group1 works as x-axis, group2 works as y-axis, composition works as size and p-value as color if provided; x-axis could also be some continuous values)
- Lollipop plots (just like dot plots, with x-axis as continuous values)
- Area plots (group1 works as x-axis, composition works as y-axis, group2 works as fill)
- Trend plots (group1 works as x-axis, composition works as y-axis, group2 works as fill)
- Sankey/Alluvial plots (groups work as nodes, composition works as edges)
- Chord/Circos plots (group1 works as source, group2 works as target, composition works as links)
- Venn Diagrams (group values expaneded as sets, composition works as overlaps)
- Upset plots (group values expaneded as sets, composition works as overlaps)
- Heatmaps (group1 works as x-axis, group2 works as y-axis, composition works as fill)
- Network plots (both group1 and group2 works as nodes, composition works as edges)

### Grouped-value plots

- Box plots (group_by works as x-axis, value works as y-axis, group_by2 works as fill if provided)
- Violin plots (group_by works as x-axis, value works as y-axis, group_by2 works as fill if provided)
- Ridge/Density plots (values as x-axis; distribution and group_by as y-axis)
- Strip plots (group_by works as x-axis, value works as y-axis, group_by2 works as fill if provided)
- Heatmaps (group1 works as x-axis, group2 works as y-axis, value works as fill)

### multi-value to multi-value plots

- Scatter plots
- Dimension reduction plots, a special type of scatter plots (lineage, Projection)
- Value correlation plots
- Volcano plots

### Other plots

- Enrichmap
- Wordcloud
- GSEA plots
