#' Enrichment Plot
#'
#' @description
#'  This function generates various types of plots for enrichment (over-representation) analysis.
#'
#' @param data A data frame with enrichment results generated by \code{clusterProfiler}, \code{enrichR}, or \code{enrichit}.
#' @param top_term Number of top terms to show in the plot.
#'  Default is 6 for all plots except "enrichmap" which is 100.
#' @param plot_type Type of plot to generate. Options are "bar", "dot", "lollipop", "network", "enrichmap", "wordcloud", "comparison".
#' @param metric The column name to use for the metric. Default is "p.adjust".
#' @param cutoff The cutoff value to the metric to mark the tems on the plot. Default is NULL.
#'  Note that the terms are not filtered by this value. Use \code{top_terms} to filter the terms.
#'  When specified:
#'  * 'bar' plot will show a line at the cutoff value
#'  * 'dot' plot will show gray dots for the terms above the cutoff value
#'  * 'lollipop' plot will show gray dots for the terms above the cutoff value
#'  * 'comparison' plot will show gray dots for the terms above the cutoff value
#'  * has no effect on 'network', 'enrichmap', and 'wordcloud' plots
#' @param x_by A character vector of column names to use for the x-axis. Default is NULL.
#'  Works only for "dot" and "lollipop".
#' @param size_by A character vector of column names to use for the size of the points. Default is NULL.
#'  Works only for "comparison", "dot" and "lollipop".
#' @param fill_cutoff_name The legend name for the terms above the cutoff value. Default is NULL.
#'  Works only for "comparison", "dot" and "lollipop".
#' @param fill_name The legend name for the metric. Default is NULL.
#'  Works only for "comparison", "dot" and "lollipop".
#' @param character_width The width of the terms in the plot. Default is 50.
#'  When the terms are too long, they will be wrapped to fit the width.
#' @param expand A numeric vector of length 1, 2 or 4 to expand the plot. Default is NULL.
#'  Works only for "bar" plot.
#'  See also [plotthis::BarPlot].
#' @param word_type The type of word to show in the wordcloud. Options are "term" and "feature". Default is "term".
#'  Works only for "wordcloud".
#' @param split_by A character vector of column names to split the plots. Default is NULL.
#' @param split_by_sep A character to separate the split_by column names. Default is "_".
#' @param facet_by A character vector of column names to facet the plots. Default is NULL.
#' @param facet_scales The facet scales. Default is NULL.
#' @param group_by A character vector of column names to group the terms. Default is NULL.
#'  Works only for "comparison" plot.
#' @param group_by_sep A character to concatenate the group_by columns when there are multiple columns. Default is "_".
#'  Works only for "comparison" plot.
#' @param palette The color palette to use for the plot. Default is "Spectral".
#'  See [plotthis::show_palettes] for available palettes.
#' @param xlab The x-axis label. Default is NULL.
#' @param ylab The y-axis label. Default is NULL.
#' @param ... Other arguments passed to the specific plot function.
#'  * For "bar", [plotthis::BarPlot()].
#'  * For "dot", [plotthis::DotPlot()].
#'  * For "lollipop", [plotthis::LollipopPlot()].
#'  * For "network", [plotthis::EnrichNetwork()].
#'  * For "enrichmap", [plotthis::EnrichMap()].
#'  * For "wordcloud", [plotthis::WordCloudPlot()].
#'  * For "comparison", [plotthis::DotPlot()].
#' @importFrom rlang sym syms
#' @importFrom stringr str_wrap
#' @importFrom dplyr %>% group_by slice_min ungroup
#' @importFrom plotthis BarPlot DotPlot LollipopPlot EnrichNetwork EnrichMap WordCloudPlot
#' @export
#' @examples
#' set.seed(8525)
#' data(enrich_example, package = "plotthis")
#' data(enrich_multidb_example, package = "plotthis")
#'
#' EnrichmentPlot(enrich_example)
#' EnrichmentPlot(enrich_example, cutoff = 0.05)
#' EnrichmentPlot(enrich_example, palette = "Paired")
#'
#' # Multiple databases#'
#' EnrichmentPlot(enrich_multidb_example, facet_by = "Database", facet_nrow = 2)
#'
#' enrich_example$Group <- sample(c("A", "B"), nrow(enrich_example), replace = TRUE)
#' EnrichmentPlot(enrich_example, plot_type = "comparison", group_by = "Group")
#' EnrichmentPlot(enrich_example, plot_type = "dot", top_term = 10)
#' EnrichmentPlot(enrich_example, plot_type = "lollipop", top_term = 10)
#' EnrichmentPlot(enrich_example, plot_type = "network")
#' EnrichmentPlot(enrich_example, plot_type = "enrichmap")
#' EnrichmentPlot(enrich_example, plot_type = "wordcloud")
#' # Wordcloud with feature
#' EnrichmentPlot(enrich_example, plot_type = "wordcloud", word_type = "feature")
EnrichmentPlot <- function(
    data, top_term = NULL,
    plot_type = c("bar", "dot", "lollipop", "network", "enrichmap", "wordcloud", "comparison"),
    x_by = NULL, size_by = NULL, fill_cutoff_name = NULL, fill_name = NULL,
    character_width = 50, expand = NULL, word_type = c("term", "feature"),
    split_by = NULL, split_by_sep = "_", facet_by = NULL, facet_scales = NULL,
    group_by = NULL, group_by_sep = "_", metric = "p.adjust", cutoff = NULL,
    palette = "Spectral", xlab = NULL, ylab = NULL,
    ...
) {
    if (all(c("pvalue", "p.adjust", "qvalue") %in% colnames(data))) {
        in_form <- "clusterProfiler"
    } else if (all(c("P.value", "Adjusted.P.value") %in% colnames(data))) {
        in_form <- "enrichr"
    } else {
        stop("[EnrichmentPlot] Cannot infer the input data format. The data should be the output of either 'clusterProfiler' or 'enrichr'.")
    }

    if (in_form == "enrichr") {
        data <- utils::getFromNamespace("prepare_enrichr_result", "plotthis")(data)
    }

    descr_col <- "Description"
    plot_type <- match.arg(plot_type)
    split_by <- check_columns(
        data, split_by, force_factor = TRUE, allow_multi = TRUE,
        concat_multi = TRUE, concat_sep = split_by_sep
    )
    group_by <- check_columns(
        data, group_by, force_factor = TRUE, allow_multi = TRUE,
        concat_multi = TRUE, concat_sep = group_by_sep
    )
    facet_by <- check_columns(
        data, facet_by, force_factor = TRUE, allow_multi = TRUE
    )
    descr_col <- check_columns(data, descr_col, force_factor = TRUE)

    top_term <- top_term %||% ifelse(plot_type == "enrichmap", 100 , 6)
    # if (!is.null(cutoff)) {
    #     data <- data[data[[metric]] < cutoff, , drop = FALSE]
    # }

    # Keep the top terms for each split_by, group_by, and facet_by
    if (!is.null(split_by) || !is.null(group_by) || !is.null(facet_by)) {
        data <- data %>%
            group_by(!!!syms(unique(c(split_by, group_by, facet_by)))) %>%
            slice_min(!!sym(metric), n = top_term, with_ties = FALSE) %>%
            ungroup()
    } else {
        data <- data %>% slice_min(!!sym(metric), n = top_term, with_ties = FALSE)
    }

    # preprocessing
    if (plot_type %in% c("bar", "comparison", "dot", "lollipop")) {
        data$.metric <- -log10(data[[metric]])
        # we lost order?
        data[[descr_col]] <- str_wrap(data[[descr_col]], width = character_width)
        # Convert GeneRatio from something like "38/225" to 0.169
        data$GeneRatio <- as.numeric(sapply(strsplit(data$GeneRatio, "/"), function(x) as.numeric(x[1]) / as.numeric(x[2])))
        if (!is.null(data$BgRatio) && !all(is.na(data$BgRatio))) {
            data$BgRatio <- as.numeric(sapply(strsplit(data$BgRatio, "/"), function(x) as.numeric(x[1]) / as.numeric(x[2])))
        }
    }

    if (plot_type == "bar") {
        if (!is.null(group_by)) {
            stop("'group_by' is not supported for Enrichment bar plot. Use 'facet_by'/'split_by' to split the plots.")
        }
        expand <- expand %||% c(0.1, 0.6, 0, 0.6)
        if (!is.null(cutoff)) {
            add_line <- -log10(cutoff)
            line_name <- paste0(metric, " = ", cutoff)
        } else {
            add_line <- NULL
            line_name <- NULL
        }
        BarPlot(data, x = descr_col, y = ".metric", flip = TRUE, label = "Count",
            add_line = add_line, line_name = line_name,
            label_nudge = 0.8, fill_by_x_if_no_group = FALSE, palette = palette, expand = expand,
            split_by = split_by, facet_by = facet_by, facet_scales = facet_scales %||% "free_y",
            ylab = xlab %||% paste0("-log10(", metric, ")"), xlab = ylab %||% "", ...)
    } else if (plot_type == "comparison") {
        if (is.null(group_by)) {
            stop("'group_by' is required for Enrichment comparison plot.")
        }
        size_by <- size_by %||% "GeneRatio"
        if (!is.null(cutoff)) {
            fill_cutoff <- -log10(cutoff)
            fill_cutoff_name <- fill_cutoff_name %||% "Non-significant"
        } else {
            fill_cutoff <- NULL
            fill_cutoff_name <- fill_cutoff_name
        }
        DotPlot(data, x = group_by, y = descr_col, fill_by = ".metric",
            fill_cutoff = fill_cutoff, fill_cutoff_name = fill_cutoff_name,
            size_by = size_by, palette = palette, fill_name = fill_name %||% paste0("-log10(", metric, ")"),
            split_by = split_by, facet_by = facet_by, facet_scales = facet_scales %||% "free_y",
            xlab = xlab %||% "", ylab = ylab %||% group_by, ...)
    } else if (plot_type == "dot") {
        if (!is.null(group_by)) {
            stop("'group_by' is not supported for Enrichment dot plot. Use 'facet_by'/'split_by' to split the plots.")
        }
        x_by <- x_by %||% "GeneRatio"
        size_by <- size_by %||% "Count"
        if (!is.null(cutoff)) {
            fill_cutoff <- -log10(cutoff)
            fill_cutoff_name <- fill_cutoff_name %||% "Non-significant"
        } else {
            fill_cutoff <- NULL
            fill_cutoff_name <- fill_cutoff_name
        }
        DotPlot(data, x = x_by, y = descr_col, fill_by = ".metric",
            fill_cutoff = fill_cutoff, fill_cutoff_name = fill_cutoff_name,
            size_by = size_by, palette = palette, fill_name = fill_name %||% paste0("-log10(", metric, ")"),
            split_by = split_by, facet_by = facet_by, facet_scales = facet_scales %||% "free_y",
            xlab = xlab %||% x_by, ylab = ylab %||% "", ...)
    } else if (plot_type == "lollipop") {
        if (!is.null(group_by)) {
            stop("'group_by' is not supported for Enrichment lollipop plot. Use 'facet_by'/'split_by' to split the plots.")
        }
        x_by <- x_by %||% "GeneRatio"
        size_by <- size_by %||% "Count"
        if (!is.null(cutoff)) {
            fill_cutoff <- -log10(cutoff)
            fill_cutoff_name <- fill_cutoff_name %||% "Non-significant"
        } else {
            fill_cutoff <- NULL
            fill_cutoff_name <- fill_cutoff_name
        }
        LollipopPlot(data, x = x_by, y = descr_col, fill_by = ".metric",
            fill_cutoff = fill_cutoff, fill_cutoff_name = fill_cutoff_name,
            size_by = size_by, fill_name = fill_name %||% paste0("-log10(", metric, ")"),
            palette = palette, split_by = split_by, facet_by = facet_by, facet_scales = facet_scales %||% "free_y",
            xlab = xlab %||% x_by, ylab = ylab %||% "", ...)
    } else if (plot_type == "network") {
        if (!is.null(group_by)) {
            stop("'group_by' is not supported for Enrichment network plot. Use 'facet_by'/'split_by' to split the plots.")
        }
        EnrichNetwork(data, in_form = "clusterProfiler", character_width = character_width, split_by = split_by,
            facet_by = facet_by, facet_scales = facet_scales, metric = metric, palette = palette, xlab = xlab, ylab = ylab, ...)
    } else if (plot_type == "enrichmap") {
        if (!is.null(group_by)) {
            stop("'group_by' is not supported for Enrichment enrichmap plot. Use 'facet_by'/'split_by' to split the plots.")
        }
        EnrichMap(data, in_form = "clusterProfiler", character_width = character_width, split_by = split_by,
            facet_by = facet_by, facet_scales = facet_scales, metric = metric, palette = palette, xlab = xlab, ylab = ylab, ...)
    } else if (plot_type == "wordcloud") {
        if (!is.null(group_by)) {
            stop("'group_by' is not supported for Enrichment wordcloud plot. Use 'facet_by'/'split_by' to split the plots.")
        }
        word_type <- match.arg(word_type)
        data$.metric <- -log10(data[[metric]])
        if (word_type == "feature") {
            data$Genes <- lapply(data$geneID, gsub, pattern = "/", replacement = " ", fixed = TRUE)
            WordCloudPlot(data, sentence_by = "Genes", score_name = paste0("sum(-log10(", metric, "))"),
                split_by = split_by, facet_by = facet_by, score_by = ".metric", score_agg = sum,
                facet_scales = facet_scales, palette = palette, xlab = xlab, ylab = ylab, ...)
        } else {
            WordCloudPlot(data, sentence_by = descr_col, score_name = paste0("sum(-log10(", metric, "))"),
                split_by = split_by, facet_by = facet_by, score_by = ".metric", score_agg = sum,
                facet_scales = facet_scales, palette = palette, xlab = xlab, ylab = ylab, ...)
        }
    }
}
